<script setup lang="ts">
import { computed } from 'vue'
import { getScholarship } from '../data/scholarships'
import { useAppState } from '../composables/useAppState'
import BaseProgress from '../components/common/BaseProgress.vue'
import { CalendarDays, CircleCheck, PartyPopper, FileQuestion, ExternalLink } from 'lucide-vue-next'
const { checklist, progress, selectedId, toast } = useAppState()
const selected = computed(() => selectedId.value ? getScholarship(selectedId.value) : undefined)
const days = computed(() => selected.value ? Math.max(0,Math.ceil((new Date(selected.value.deadline).getTime()-Date.now())/86400000)) : 0)
const categories = computed(() => [...new Set(checklist.value.map((item) => item.category))])
const markHave = (id:string) => { const item=checklist.value.find((entry)=>entry.id===id); if(item){item.completed=true; toast(`Marked ${item.title} as ready.`)} }
</script>
<template><main><section class="border-b border-slate-200 bg-gradient-to-b from-[#f6f4ff] to-white py-16"><div class="container"><p class="eyebrow">Stay organized</p><div class="mt-5 grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div><h1 class="page-title">Your application checklist</h1><p class="mt-5 max-w-2xl text-lg leading-8 text-slate-500">Complete items using documents you already have. Preparation tools are optional and never required to mark progress.</p></div><div v-if="selected" class="card px-5 py-4"><p class="text-xs font-bold text-slate-400">Selected scholarship</p><p class="mt-1 font-extrabold text-[#17136b]">{{ selected.name }}</p></div></div></div></section>
<section class="section pt-12"><div class="container max-w-4xl"><div v-if="progress === 100" class="mb-7 rounded-3xl bg-gradient-to-r from-emerald-500 to-teal-500 p-7 text-white"><PartyPopper :size="28"/><h2 class="mt-4 text-2xl font-extrabold">You’re application-ready!</h2><p class="mt-2 text-emerald-50">Every checklist item is marked complete. Review official requirements one final time before submitting.</p></div><div v-if="!selected" class="card mb-8 flex flex-col items-center p-10 text-center"><FileQuestion class="text-slate-300" :size="34"/><h2 class="mt-4 text-xl font-extrabold text-[#17136b]">Choose a scholarship to personalize this checklist</h2><p class="mt-2 text-sm text-slate-500">You can still use the standard checklist below.</p><RouterLink to="/scholarships" class="btn-primary mt-5">Select a scholarship</RouterLink></div>
<div class="card p-6 sm:p-8"><div class="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-end"><div><BaseProgress :value="progress" label="Overall progress"/><p class="mt-3 text-sm text-slate-500">{{ checklist.filter(i=>i.completed).length }} of {{ checklist.length }} tasks ready</p></div><div v-if="selected" class="rounded-2xl bg-violet-50 px-5 py-4"><div class="flex items-center gap-2 text-xs font-bold text-[#5b45f5]"><CalendarDays :size="15"/>Deadline countdown</div><p class="mt-2 text-2xl font-extrabold text-[#17136b]">{{ days }} days</p></div></div></div>
<section v-for="category in categories" :key="category" class="mt-9"><h2 class="mb-4 text-sm font-extrabold uppercase tracking-[.14em] text-slate-400">{{ category }}</h2><div class="grid gap-3"><article v-for="item in checklist.filter(entry=>entry.category===category)" :key="item.id" class="card p-5"><div class="flex items-start gap-4"><label class="mt-1 cursor-pointer"><input v-model="item.completed" type="checkbox" class="size-5 accent-[#5b45f5]" :aria-label="`Mark ${item.title} complete`"></label><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h3 class="font-extrabold text-[#17136b]" :class="item.completed && 'line-through opacity-60'">{{ item.title }}</h3><span class="tag">{{ item.required ? 'Required' : 'Optional' }}</span></div><textarea v-model="item.notes" class="field mt-3 min-h-20 resize-y text-sm" :aria-label="`Notes for ${item.title}`" placeholder="Add a private note for this item..."></textarea><div class="mt-3 flex flex-wrap gap-3"><button class="text-xs font-bold text-[#5b45f5]" @click="markHave(item.id)">I already have this</button><RouterLink v-if="['cv','essay','ielts'].includes(item.id)" :to="item.id==='ielts'?'/practice':'/documents'" class="inline-flex items-center gap-1 text-xs font-bold text-slate-500">Optional preparation help <ExternalLink :size="12"/></RouterLink></div></div><CircleCheck v-if="item.completed" class="text-emerald-500" :size="21"/></div></article></div></section>
<p class="mt-8 text-center text-xs text-slate-400">Progress and notes are stored only in this browser.</p></div></section></main></template>
