<script setup lang="ts">
import { computed } from 'vue'
import { LayoutDashboard, Search, ClipboardCheck, FileText, Headphones, Users, WalletCards, CalendarDays, ArrowRight, Bookmark, Sparkles, Clock3 } from 'lucide-vue-next'
import { scholarships, getScholarship } from '../data/scholarships'
import { useAppState } from '../composables/useAppState'
import BaseProgress from '../components/common/BaseProgress.vue'
import ScholarshipCard from '../components/scholarships/ScholarshipCard.vue'
const { profile, session, selectedId, savedIds, progress, booking, practiceResult } = useAppState()
const selected = computed(() => selectedId.value ? getScholarship(selectedId.value) : undefined)
const saved = computed(() => scholarships.filter((item) => savedIds.value.includes(item.id)))
const days = computed(() => selected.value ? Math.max(0, Math.ceil((new Date(selected.value.deadline).getTime()-Date.now())/86400000)) : 0)
</script>
<template><main class="bg-[#fbfbfe] py-10 sm:py-14"><div class="container dashboard-layout"><aside class="dashboard-side card"><p class="px-3 pb-3 text-xs font-extrabold uppercase tracking-wider text-slate-400">Workspace</p><RouterLink to="/dashboard" class="side-link active"><LayoutDashboard :size="17"/>Overview</RouterLink><RouterLink to="/scholarships" class="side-link"><Search :size="17"/>Discover</RouterLink><RouterLink to="/checklist" class="side-link"><ClipboardCheck :size="17"/>Checklist</RouterLink><RouterLink to="/documents" class="side-link"><FileText :size="17"/>Documents</RouterLink><RouterLink to="/practice" class="side-link"><Headphones :size="17"/>Practice</RouterLink><RouterLink to="/mentors" class="side-link"><Users :size="17"/>Mentors</RouterLink></aside>
<div class="min-w-0"><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Student dashboard</p><h1 class="mt-4 text-4xl font-extrabold tracking-tight text-[#17136b]">Welcome back, {{ profile?.name || session?.name || 'Maya' }}</h1><p class="mt-3 text-slate-500">Here’s what deserves your attention next.</p></div><RouterLink to="/scholarships" class="btn-primary">Find scholarships <ArrowRight :size="16"/></RouterLink></div>
<div class="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="dash-card"><div class="flex items-center justify-between"><span class="text-xs font-bold text-slate-400">Profile completion</span><Sparkles :size="17" class="text-[#5b45f5]"/></div><p class="mt-4 text-3xl font-extrabold text-[#17136b]">{{ profile ? '100%' : '68%' }}</p><RouterLink to="/onboarding" class="mt-2 inline-block text-xs font-bold text-[#5b45f5]">{{ profile ? 'Review profile' : 'Complete profile' }}</RouterLink></div><div class="dash-card"><div class="flex items-center justify-between"><span class="text-xs font-bold text-slate-400">Saved scholarships</span><Bookmark :size="17" class="text-[#5b45f5]"/></div><p class="mt-4 text-3xl font-extrabold text-[#17136b]">{{ saved.length }}</p><p class="mt-2 text-xs text-slate-400">Your shortlist</p></div><div class="dash-card"><div class="flex items-center justify-between"><span class="text-xs font-bold text-slate-400">Checklist</span><ClipboardCheck :size="17" class="text-emerald-500"/></div><p class="mt-4 text-3xl font-extrabold text-[#17136b]">{{ progress }}%</p><RouterLink to="/checklist" class="mt-2 inline-block text-xs font-bold text-[#5b45f5]">Continue checklist</RouterLink></div><div class="dash-card"><div class="flex items-center justify-between"><span class="text-xs font-bold text-slate-400">Token balance</span><WalletCards :size="17" class="text-amber-500"/></div><p class="mt-4 text-3xl font-extrabold text-[#17136b]">12</p><p class="mt-2 text-xs text-slate-400">Demo tokens</p></div></div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section class="card p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-extrabold text-[#17136b]">Selected scholarship</h2><RouterLink to="/checklist" class="text-xs font-bold text-[#5b45f5]">Open checklist</RouterLink></div><div v-if="selected" class="mt-6"><span class="badge">{{ selected.matchPercentage }}% match</span><h3 class="mt-4 text-2xl font-extrabold text-[#17136b]">{{ selected.name }}</h3><p class="mt-2 text-sm text-slate-500">{{ selected.provider }} · {{ selected.country }}</p><div class="mt-6"><BaseProgress :value="progress" label="Application readiness"/></div><div class="mt-5 flex flex-wrap gap-3"><span class="tag"><CalendarDays :size="14"/>{{ days }} days left</span><RouterLink :to="`/scholarships/${selected.id}`" class="tag">View details</RouterLink></div></div><div v-else class="mt-6 rounded-2xl border border-dashed border-slate-300 p-8 text-center"><Search class="mx-auto text-slate-300"/><h3 class="mt-4 font-extrabold text-[#17136b]">No scholarship selected</h3><p class="mt-2 text-sm text-slate-500">Choose an opportunity to build a focused preparation plan.</p><RouterLink to="/scholarships" class="btn-primary mt-5">Explore matches</RouterLink></div></section>
<section class="card p-6"><h2 class="text-xl font-extrabold text-[#17136b]">Upcoming deadlines</h2><div class="mt-5 grid gap-4"><div v-for="item in scholarships.slice(0,3)" :key="item.id" class="flex gap-3 border-b border-slate-100 pb-4"><span class="grid size-10 place-items-center rounded-xl bg-violet-50 text-[#5b45f5]"><CalendarDays :size="17"/></span><div><p class="text-sm font-bold text-[#17136b]">{{ item.name }}</p><p class="mt-1 text-xs text-slate-400">{{ item.deadline }}</p></div></div></div></section></div>
<div class="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3"><section class="card p-6"><FileText :size="20" class="text-[#5b45f5]"/><h2 class="mt-4 font-extrabold text-[#17136b]">Document reviews</h2><p class="mt-2 text-sm text-slate-500">CV: 82 demo score · Essay: not reviewed</p><RouterLink to="/documents" class="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#5b45f5]">Open optional tools <ArrowRight :size="13"/></RouterLink></section><section class="card p-6"><Headphones :size="20" class="text-[#27a8f7]"/><h2 class="mt-4 font-extrabold text-[#17136b]">IELTS progress</h2><p class="mt-2 text-sm text-slate-500">{{ practiceResult ? `${practiceResult.score}% on ${practiceResult.type}` : 'No practice result yet' }}</p><RouterLink to="/practice" class="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#5b45f5]">Practice now <ArrowRight :size="13"/></RouterLink></section><section class="card p-6"><Users :size="20" class="text-amber-500"/><h2 class="mt-4 font-extrabold text-[#17136b]">Mentor booking</h2><p class="mt-2 text-sm text-slate-500">{{ booking ? `${booking.mentorName} · ${booking.date} at ${booking.time}` : 'No upcoming session' }}</p><RouterLink to="/mentors" class="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#5b45f5]">{{ booking ? 'Manage booking' : 'Find a mentor' }} <ArrowRight :size="13"/></RouterLink></section></div>
<section class="card mt-6 p-6"><h2 class="text-xl font-extrabold text-[#17136b]">Recent activity</h2><div class="mt-5 grid gap-3 sm:grid-cols-3"><div v-for="item in [{icon:Clock3,text:'Viewed Chevening details',time:'Today'},{icon:Bookmark,text:'Updated your shortlist',time:'Yesterday'},{icon:ClipboardCheck,text:'Completed transcript task',time:'2 days ago'}]" :key="item.text" class="flex items-center gap-3 rounded-xl bg-slate-50 p-4"><component :is="item.icon" :size="17" class="text-[#5b45f5]"/><div><p class="text-sm font-bold text-[#17136b]">{{ item.text }}</p><p class="text-xs text-slate-400">{{ item.time }}</p></div></div></div></section>
<section class="mt-12"><div class="flex items-end justify-between"><div><p class="eyebrow">Recommended for you</p><h2 class="mt-3 text-2xl font-extrabold text-[#17136b]">Strong profile matches</h2></div></div><div class="mt-6 grid gap-5 lg:grid-cols-3"><ScholarshipCard v-for="item in scholarships.slice(0,3)" :key="item.id" :scholarship="item" compact/></div></section></div></div></main></template>
