<script setup lang="ts">
import { computed, ref } from 'vue'
import { UploadCloud, FileText, WandSparkles, CircleCheck, AlertCircle } from 'lucide-vue-next'
import SectionHeader from '../components/common/SectionHeader.vue'
import { useAppState } from '../composables/useAppState'
const active=ref<'cv'|'essay'>('cv'), dragging=ref(false), fileName=ref(''), error=ref(''), processing=ref(false), cvDone=ref(false), essay=ref(''), essayDone=ref(false)
const { toast }=useAppState(); const count=computed(()=>essay.value.length)
const processFile=(file?:File)=>{ error.value=''; if(!file)return; if(file.type!=='application/pdf'){error.value='Please choose a PDF file.';return} if(file.size>2*1024*1024){error.value='This file is over the 2 MB demo limit.';return} fileName.value=file.name }
const fileChange=(event:Event)=>processFile((event.target as HTMLInputElement).files?.[0])
const drop=(event:DragEvent)=>{dragging.value=false;processFile(event.dataTransfer?.files[0])}
const reviewCv=()=>{if(!fileName.value){error.value='Choose a PDF before starting the review.';return}processing.value=true;setTimeout(()=>{processing.value=false;cvDone.value=true;toast('Your mock CV feedback is ready.')},1000)}
const reviewEssay=()=>{if(count.value<120){error.value='Add at least 120 characters for a useful demo review.';return}error.value='';processing.value=true;setTimeout(()=>{processing.value=false;essayDone.value=true;toast('Your mock essay feedback is ready.')},1000)}
const cvFeedback=[['Completeness','Strong education and contact sections; add your expected graduation date.'],['Formatting','Clear hierarchy. Reduce the profile paragraph to three lines.'],['Experience','Good action verbs; quantify the impact of two projects.'],['Achievements','Move the national case competition into a dedicated achievements section.'],['Skills','Group technical and language skills separately.'],['Scholarship relevance','Bring leadership and community impact closer to the top.']]
const essayFeedback=[['Structure','Your opening is focused, but the second section needs a clearer topic sentence.'],['Relevance','Examples connect well to public policy and development goals.'],['Clarity','Shorten several sentences to make the argument easier to follow.'],['Grammar','Mostly accurate; review article use and parallel structure.'],['Motivation','Your motivation feels specific and grounded in lived experience.'],['Personal impact','Add one measurable result from your community initiative.'],['Scholarship alignment','Explain more directly how the program’s network supports your return plan.']]
</script>
<template><main><section class="border-b border-slate-200 bg-gradient-to-b from-[#f6f4ff] to-white py-18"><div class="container"><SectionHeader eyebrow="Stronger applications" title="Improve your documents before you submit" body="Use a safe frontend simulation to preview structured feedback. Files never leave your device and no real AI service is called."/></div></section><section class="section pt-12"><div class="container max-w-5xl"><div class="mb-8 inline-flex rounded-xl bg-slate-100 p-1" role="tablist"><button v-for="tab in [{id:'cv',label:'CV Review'},{id:'essay',label:'Essay Review'}]" :key="tab.id" class="rounded-lg px-5 py-2.5 text-sm font-extrabold" :class="active===tab.id?'bg-white text-[#5b45f5] shadow-sm':'text-slate-500'" role="tab" :aria-selected="active===tab.id" @click="active=tab.id as 'cv'|'essay';error=''">{{ tab.label }}</button></div>
<div v-if="active==='cv'" class="grid gap-7 lg:grid-cols-2"><div><div class="upload-zone p-7" :class="dragging&&'dragging'" @dragover.prevent="dragging=true" @dragleave="dragging=false" @drop.prevent="drop"><div><UploadCloud class="mx-auto text-[#5b45f5]" :size="34"/><h2 class="mt-5 text-xl font-extrabold text-[#17136b]">Drop your CV here</h2><p class="mt-2 text-sm text-slate-500">PDF only · Maximum 2 MB · Local demo</p><label class="btn-secondary mt-5 cursor-pointer"><input type="file" accept="application/pdf" class="sr-only" @change="fileChange">Choose PDF</label><p v-if="fileName" class="mt-4 text-sm font-bold text-emerald-600">{{ fileName }}</p></div></div><p v-if="error" class="error mt-3 flex items-center gap-2"><AlertCircle :size="15"/>{{ error }}</p><button class="btn-primary mt-5" :disabled="processing" @click="reviewCv"><WandSparkles :size="17"/>{{ processing?'Analyzing demo…':'Review my CV' }}</button></div><div class="card p-7"><div v-if="!cvDone" class="grid min-h-[360px] place-items-center text-center"><div><FileText class="mx-auto text-slate-300" :size="38"/><h2 class="mt-5 text-xl font-extrabold text-[#17136b]">Feedback appears here</h2><p class="mt-2 text-sm text-slate-500">Choose a valid PDF and run the simulated review.</p></div></div><div v-else><div class="flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Optional demo score</p><p class="mt-2 text-5xl font-extrabold text-[#5b45f5]">82<span class="text-lg text-slate-400">/100</span></p></div><CircleCheck class="text-emerald-500" :size="28"/></div><div class="mt-7 grid gap-4"><div v-for="item in cvFeedback" :key="item[0]"><h3 class="text-sm font-extrabold text-[#17136b]">{{ item[0] }}</h3><p class="mt-1 text-sm leading-6 text-slate-500">{{ item[1] }}</p></div></div></div></div></div>
<div v-else class="grid gap-7 lg:grid-cols-2"><div><label class="field-label">Essay or personal statement<textarea v-model="essay" class="field min-h-[360px] resize-y font-normal leading-7" placeholder="Paste your essay here. This text remains in your browser."></textarea></label><div class="mt-2 flex justify-between text-xs text-slate-400"><span>Optional uploads are simulated in the CV tab.</span><span>{{ count.toLocaleString() }} characters</span></div><p v-if="error" class="error mt-3 flex items-center gap-2"><AlertCircle :size="15"/>{{ error }}</p><button class="btn-primary mt-5" :disabled="processing" @click="reviewEssay"><WandSparkles :size="17"/>{{ processing?'Reviewing demo…':'Review my essay' }}</button></div><div class="card p-7"><div v-if="!essayDone" class="grid min-h-[430px] place-items-center text-center"><div><WandSparkles class="mx-auto text-slate-300" :size="38"/><h2 class="mt-5 text-xl font-extrabold text-[#17136b]">Structured guidance appears here</h2><p class="mt-2 text-sm text-slate-500">Add your text to see predetermined demo feedback.</p></div></div><div v-else><div class="flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Optional demo score</p><p class="mt-2 text-5xl font-extrabold text-[#5b45f5]">78<span class="text-lg text-slate-400">/100</span></p></div><CircleCheck class="text-emerald-500" :size="28"/></div><div class="mt-7 grid gap-4"><div v-for="item in essayFeedback" :key="item[0]"><h3 class="text-sm font-extrabold text-[#17136b]">{{ item[0] }}</h3><p class="mt-1 text-sm leading-6 text-slate-500">{{ item[1] }}</p></div></div></div></div></div>
<p class="mt-8 rounded-2xl bg-amber-50 p-4 text-center text-xs leading-5 text-amber-800">AI-style feedback supports your preparation. You remain responsible for the final version. This demo does not upload or analyze files with an external service.</p></div></section></main></template>
