<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
import { ArrowLeft, BarChart3, CheckCircle2, CircleStop, Clock3, Mic, Pause, Play, UploadCloud, Video } from 'lucide-vue-next'
import WorkspaceSidebar from '../components/workspace/WorkspaceSidebar.vue'
import WorkspaceTopbar from '../components/workspace/WorkspaceTopbar.vue'
import { getScholarship } from '../data/scholarships'
import { useAppState } from '../composables/useAppState'
type Stage='setup'|'language'|'live'|'results'
const { selectedId, toast }=useAppState();const selected=computed(()=>selectedId.value?getScholarship(selectedId.value):undefined);const stage=ref<Stage>('setup'),fileName=ref(''),context=ref(''),language=ref<'Bahasa Indonesia'|'English'>('Bahasa Indonesia'),isPaused=ref(false),elapsed=ref(0),questionIndex=ref(0);let timer:number|undefined
const questions=computed(()=>selected.value?[`Tell us why ${selected.value.name} matches your academic and leadership goals.`,`Describe a challenge that proves you are ready to study in ${selected.value.country}.`,`How will you use this opportunity to create measurable impact after graduation?`]:[]);const question=computed(()=>questions.value[questionIndex.value]||'');const formatted=computed(()=>`${String(Math.floor(elapsed.value/60)).padStart(2,'0')}:${String(elapsed.value%60).padStart(2,'0')}`);const upload=(e:Event)=>{const f=(e.target as HTMLInputElement).files?.[0];if(f)fileName.value=f.name};const continueSetup=()=>{if(!selected.value){toast('Select a scholarship before interview preparation.','info');return}if(!fileName.value){toast('Import a CV, personal statement, or application document first.','info');return}stage.value='language'};const start=()=>{stage.value='live';isPaused.value=false;timer=window.setInterval(()=>{if(!isPaused.value)elapsed.value++},1000)};const finish=()=>{if(timer)window.clearInterval(timer);timer=undefined;stage.value='results';toast('Interview analysis is ready.')};const nextQuestion=()=>questionIndex.value=Math.min(questions.value.length-1,questionIndex.value+1);onBeforeUnmount(()=>{if(timer)window.clearInterval(timer)})
</script>
<template><main class="workspace-shell"><WorkspaceSidebar active="interview"/><div class="workspace-main"><WorkspaceTopbar title="Interview Prep" subtitle="Scholarship-specific setup, live practice, and performance analysis."/><div class="workspace-content">
  <section v-if="stage==='setup'" class="interview-setup"><div class="interview-step"><span>1</span><i/><span>2</span></div><p class="eyebrow">Personal background</p><h2>Prepare a tailored interview</h2><p>Selecting a scholarship and importing a document lets Minerva tailor questions to your goals and experience.</p><div class="interview-setup-grid"><div class="workspace-card p-6"><p class="text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Selected scholarship</p><div v-if="selected" class="mt-4"><h3 class="text-xl font-extrabold text-[#17136b]">{{ selected.name }}</h3><p class="mt-2 text-sm text-slate-500">{{ selected.provider }} · {{ selected.country }}</p></div><div v-else class="mt-4"><p class="text-sm text-slate-500">Choose a scholarship before continuing.</p><RouterLink to="/scholarships" class="btn-secondary mt-4">Select scholarship</RouterLink></div><label class="interview-upload"><UploadCloud :size="30"/><strong>{{ fileName||'Import your document' }}</strong><span>CV, personal statement, essay, study plan, or research plan</span><input type="file" class="sr-only" accept=".pdf,.doc,.docx" @change="upload"></label></div><div class="workspace-card p-6"><p class="text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Additional context</p><textarea v-model="context" class="field mt-4 min-h-56" placeholder="Add goals, focus areas, or context the interviewer should know…"/><div class="mt-5 rounded-xl bg-emerald-50 p-4 text-xs leading-5 text-emerald-800">Your imported file stays on this device in this frontend simulation.</div></div></div><button class="btn-primary ml-auto mt-6" @click="continueSetup">Continue to language<Play :size="16"/></button></section>
  <section v-else-if="stage==='language'" class="interview-language"><div class="interview-step"><span>1</span><i class="active"/><span>2</span></div><p class="eyebrow">Interview language</p><h2>Choose the language you will use</h2><label v-for="item in ['Bahasa Indonesia','English']" :key="item" class="interview-language-option" :class="language===item&&'active'"><input v-model="language" type="radio" :value="item"><div><strong>{{ item }}</strong><p>{{ item==='Bahasa Indonesia'?'Interview questions and guidance in Indonesian.':'Interview questions and guidance in English.' }}</p></div></label><div class="mt-7 flex justify-between"><button class="btn-secondary" @click="stage='setup'"><ArrowLeft :size="16"/>Back</button><button class="btn-primary" @click="start">Start interview<Play :size="16"/></button></div></section>
  <section v-else-if="stage==='live'" class="interview-live"><header><div><p>{{ selected?.name }}</p><span>{{ language }} · tailored question {{ questionIndex+1 }}/{{ questions.length }}</span></div><span class="live-pulse">{{ isPaused?'Paused':'Connected' }}</span><strong>{{ formatted }}</strong></header><div class="interview-stage"><div class="interview-video"><div class="face-outline"><span/></div><small>You · Face Mimic Analyzer</small></div><div class="interview-ai"><div class="interview-wave"><i v-for="n in 7" :key="n" :style="{height:`${22+n%3*14}px`}"/></div><p>Minerva interviewer</p><span>Tailored to {{ selected?.provider }}</span></div></div><div class="interview-transcript"><p>{{ question }}</p><button v-if="questionIndex<questions.length-1" @click="nextQuestion">Next question</button></div><footer><button class="workspace-icon-button"><Mic :size="17"/></button><button class="workspace-icon-button"><Video :size="17"/></button><button class="workspace-icon-button" @click="isPaused=!isPaused"><Play v-if="isPaused" :size="17"/><Pause v-else :size="17"/></button><button class="btn-primary !bg-emerald-500" @click="finish"><CircleStop :size="16"/>Finish</button></footer></section>
  <section v-else class="interview-results"><header><div><p class="eyebrow">Interview results</p><h2>{{ selected?.name }}</h2></div><button class="btn-secondary" @click="stage='language';elapsed=0;questionIndex=0"><ArrowLeft :size="16"/>Practice again</button></header><div class="workspace-card p-6"><p class="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.14em] text-slate-400"><BarChart3 :size="16"/>Detailed performance analysis</p><div class="results-metrics"><div><strong>82</strong><span>Clarity score</span></div><div><strong>78</strong><span>Confidence</span></div><div><strong>86</strong><span>Structure</span></div><div><strong>142</strong><span>Words/min</span></div></div></div><div class="grid gap-5 mt-5 md:grid-cols-2"><article class="workspace-card p-6"><CheckCircle2 class="text-emerald-500"/><h3>Key highlights</h3><ul><li>Clear scholarship motivation</li><li>Strong connection to {{ selected?.provider }}</li><li>Specific post-study direction</li></ul></article><article class="workspace-card p-6"><Clock3 class="text-amber-500"/><h3>Improvement recommendations</h3><ul><li>Add a measurable impact outcome</li><li>Slow down before important examples</li><li>Use a shorter conclusion</li></ul></article></div></section>
</div></div></main></template>
