<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
import { Camera, CircleStop, Clock3, Mic, Pause, Play, Sparkles, Video, Volume2 } from 'lucide-vue-next'
import WorkspaceSidebar from '../components/dashboard/WorkspaceSidebar.vue'
import WorkspaceTopbar from '../components/dashboard/WorkspaceTopbar.vue'
import { getScholarship } from '../data/scholarships'
import { useAppState } from '../composables/useAppState'

const { selectedId, toast } = useAppState()
const selected = computed(() => selectedId.value ? getScholarship(selectedId.value) : undefined)
const isLive = ref(false), isPaused = ref(false), elapsed = ref(0), feedbackOpen = ref(false)
let timer: number | undefined
const question = computed(() => selected.value ? `Why is ${selected.value.name} the right next step for your ${selected.value.fieldOfStudy} goals, and how will you create impact after studying in ${selected.value.country}?` : 'Tell us about a challenge that shaped your academic goals. What did you learn, and how will you apply it to your scholarship journey?')
const formattedElapsed = computed(() => `${String(Math.floor(elapsed.value / 60)).padStart(2, '0')}:${String(elapsed.value % 60).padStart(2, '0')}`)
const start = () => { isLive.value = true; isPaused.value = false; if (!timer) timer = window.setInterval(() => { if (!isPaused.value) elapsed.value += 1 }, 1000); toast('Live interview simulation started.', 'info') }
const togglePause = () => { if (!isLive.value) return; isPaused.value = !isPaused.value }
const stop = () => { isLive.value = false; isPaused.value = false; if (timer) { window.clearInterval(timer); timer = undefined }; feedbackOpen.value = true; toast('Interview simulation ended. Demo feedback is ready.') }
onBeforeUnmount(() => { if (timer) window.clearInterval(timer) })
</script>

<template>
  <main class="workspace-shell"><WorkspaceSidebar active="interview"/><div class="workspace-main"><WorkspaceTopbar title="Interview Prep" subtitle="Practice a tailored response with controlled, simulated live feedback."/><div class="workspace-content"><section class="report-banner"><p class="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.15em] text-violet-100"><Sparkles :size="15"/>Tailored practice</p><h2 class="mt-4 max-w-3xl text-2xl font-extrabold sm:text-3xl">{{ selected ? `Prepared for ${selected.name}` : 'Select a scholarship to tailor your interview questions' }}</h2><p class="mt-3 max-w-3xl text-sm leading-6 text-violet-100">{{ selected ? `This prompt references ${selected.provider}, ${selected.country}, and your preparation goals.` : 'Until you select an opportunity, Minerva uses a strong general scholarship interview prompt.' }}</p></section>
<section class="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div class="workspace-card overflow-hidden"><div class="mimic-frame"><div class="absolute left-5 top-5"><span class="live-pulse">{{ isLive && !isPaused ? 'Live practice' : isPaused ? 'Paused' : 'Camera preview' }}</span></div><div class="face-outline"><span/></div><div class="absolute bottom-5 left-5 right-5 flex justify-between rounded-xl bg-black/25 px-4 py-3 text-xs font-bold text-white backdrop-blur"><span>Face Mimic Analyzer</span><span class="text-emerald-200">Visual demo only</span></div></div><div class="flex flex-wrap items-center justify-between gap-3 p-5"><div class="flex items-center gap-2 text-xs font-bold text-slate-500"><Camera :size="16" class="text-[#5b45f5]"/>No camera is activated in this frontend demo.</div><div class="flex items-center gap-2"><button class="workspace-icon-button" aria-label="Toggle microphone"><Mic :size="17"/></button><button class="workspace-icon-button" aria-label="Toggle speaker"><Volume2 :size="17"/></button><button class="workspace-icon-button" aria-label="Toggle video"><Video :size="17"/></button></div></div></div>
<aside class="workspace-card p-5 sm:p-6"><div class="flex items-center justify-between"><span class="badge">Tailored question</span><span class="flex items-center gap-2 text-xs font-extrabold text-slate-400"><Clock3 :size="14"/>{{ formattedElapsed }}</span></div><h2 class="mt-5 text-xl font-extrabold leading-8 text-[#17136b]">{{ question }}</h2><div class="mt-6 rounded-2xl bg-[#f5f3ff] p-4"><p class="text-xs font-extrabold uppercase tracking-[.13em] text-[#5b45f5]">Response guide</p><ul class="mt-3 grid gap-2 text-sm leading-6 text-slate-600"><li>• Begin with a concise personal motivation.</li><li>• Connect your experience to the provider’s goals.</li><li>• End with a specific impact plan after graduation.</li></ul></div><div class="mt-6 flex flex-col gap-3 sm:flex-row xl:flex-col"><button v-if="!isLive" class="btn-primary" @click="start"><Play :size="16"/>Start live practice</button><button v-else class="btn-secondary" @click="togglePause"><Play v-if="isPaused" :size="16"/><Pause v-else :size="16"/>{{ isPaused ? 'Resume' : 'Pause' }}</button><button v-if="isLive" class="btn-dark" @click="stop"><CircleStop :size="16"/>End session</button></div></aside></section>
<section class="mt-6 grid gap-5 lg:grid-cols-3"><div class="workspace-card p-5"><p class="text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Face mimic analyzer</p><p class="mt-3 text-xl font-extrabold text-[#17136b]">Engagement 84%</p><p class="mt-2 text-sm leading-6 text-slate-500">Demo signal: soften your pace and hold a little more eye-level presence.</p></div><div class="workspace-card p-5"><p class="text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Speaking pace</p><p class="mt-3 text-xl font-extrabold text-[#17136b]">142 wpm</p><p class="mt-2 text-sm leading-6 text-slate-500">Demo target range: 130–150 words per minute for clear delivery.</p></div><div class="workspace-card p-5"><p class="text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Response structure</p><p class="mt-3 text-xl font-extrabold text-[#17136b]">Ready to practice</p><p class="mt-2 text-sm leading-6 text-slate-500">Use context, action, impact, and future plan to keep your answer focused.</p></div></section>
<section v-if="feedbackOpen" class="mt-6 rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><p class="text-xs font-extrabold uppercase tracking-[.14em] text-emerald-700">Demo session summary</p><h2 class="mt-3 text-2xl font-extrabold text-emerald-950">Your response had a clear scholarship narrative.</h2><p class="mt-3 max-w-3xl text-sm leading-7 text-emerald-900">For the next attempt, make the final impact statement more measurable and connect it once more to {{ selected?.provider || 'the scholarship provider' }}’s goals. This is predetermined frontend feedback; no camera, microphone, or AI analysis was used.</p></section></div></div></main>
</template>
