<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowRight, Sparkles, Search, CircleCheck, Bookmark, CalendarDays, FileText, Headphones, Users, Target, WandSparkles, LayoutDashboard, ShieldCheck, ChevronDown } from 'lucide-vue-next'
import SectionHeader from '../components/common/SectionHeader.vue'
import BaseProgress from '../components/common/BaseProgress.vue'
import ScholarshipCard from '../components/scholarships/ScholarshipCard.vue'
import { scholarships } from '../data/scholarships'
import { useAppState } from '../composables/useAppState'

const activeFeature = ref(0)
const query = ref('')
const { checklist, progress } = useAppState()
const features = [
  { label: 'Scholarship Discovery', title: 'Find opportunities without the tab overload', body: 'Search credible programs with useful filters, clear deadlines, and the details you need to decide.', icon: Search },
  { label: 'AI Recommendations', title: 'Understand why each opportunity fits', body: 'Mock recommendations connect your background and goals to eligibility in plain language.', icon: Sparkles },
  { label: 'Application Preparation', title: 'Turn requirements into a practical plan', body: 'Build a checklist, review documents, and open optional preparation tools only when helpful.', icon: FileText },
  { label: 'Progress Tracking', title: 'Always know what deserves attention next', body: 'See progress, saved opportunities, and upcoming deadlines in one calm command center.', icon: LayoutDashboard },
]
const faq = ref<number | null>(0)
const faqs = [
  ['What is Minerva?', 'Minerva is an AI-powered scholarship discovery and preparation platform that helps users find opportunities, understand requirements, improve documents, practice, and track progress.'],
  ['Does Minerva guarantee scholarship acceptance?', 'No. Minerva provides recommendations and preparation guidance. Final decisions are always made by official scholarship providers.'],
  ['How are scholarships recommended?', 'Recommendations use profile details such as education, field, destination, funding preference, English proficiency, and eligibility requirements.'],
  ['Can Minerva submit my application?', 'No. Minerva helps you prepare and track applications, but submissions happen through each provider’s official channel.'],
  ['Can I upload my CV and essay?', 'Yes, this demo simulates local file selection and feedback. CV files must be PDFs up to 2 MB and are never uploaded.'],
  ['Is Minerva’s IELTS score official?', 'No. Practice results are unofficial and are not IELTS testing or certification.'],
  ['Can I book a mentor?', 'Yes. You can browse mentor profiles and submit a simulated booking request.'],
  ['Are payments real?', 'No. Payment and top-up flows in this MVP are simulations.'],
]
const searchResults = computed(() => scholarships.filter((item) => `${item.name} ${item.country} ${item.fieldOfStudy}`.toLowerCase().includes(query.value.toLowerCase())).slice(0, 3))
const steps = [
  ['Create your profile','Tell us about your education, goals, destination, and documents.'], ['Discover your matches','Receive recommendations based on your profile and eligibility.'],
  ['Select an opportunity','Save scholarships and choose one to prepare for.'], ['Build your checklist','See required documents, criteria, tasks, and deadlines.'],
  ['Prepare your application','Use reviews, practice, or mentor support when needed.'], ['Track your progress','Monitor completed tasks and upcoming deadlines.'],
]
</script>

<template>
  <main>
    <section class="hero-bg pb-24 pt-20 sm:pt-28">
      <div class="container relative z-10 text-center">
        <div class="fade-up mx-auto max-w-4xl">
          <p class="mx-auto mb-7 inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white/70 px-4 py-2 text-xs font-extrabold text-[#5b45f5] shadow-sm"><Sparkles :size="15" /> Your AI-powered scholarship companion</p>
          <h1 class="text-[clamp(3rem,7vw,6.6rem)] font-extrabold leading-[.96] tracking-[-.065em] text-[#17136b]">Find the right scholarship.<br><span class="gradient-text">Prepare with confidence.</span></h1>
          <p class="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-500">Minerva helps you discover scholarships that match your profile, understand every requirement, strengthen your documents, and track your application journey—all in one place.</p>
          <div class="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><RouterLink to="/register" class="btn-primary">Get Started Free <ArrowRight :size="17" /></RouterLink><RouterLink to="/scholarships" class="btn-secondary">Explore Scholarships</RouterLink></div>
          <p class="mt-5 text-xs font-semibold text-slate-400">Personalized recommendations. Guided preparation. One clear path forward.</p>
        </div>

        <div class="product-shell mx-auto mt-16 max-w-5xl text-left">
          <div class="product-panel grid min-h-[510px] grid-cols-[78px_1fr] sm:grid-cols-[180px_1fr]">
            <aside class="mini-sidebar p-4 sm:p-5"><div class="flex items-center gap-2 font-extrabold"><span class="grid size-9 place-items-center rounded-xl bg-white/12">🦉</span><span class="hidden sm:inline">Minerva</span></div><div class="mt-9 grid gap-2 text-xs text-white/65"><span class="rounded-lg bg-white/12 p-2.5 text-white">My scholarships</span><span class="p-2.5">Scholarships</span><span class="p-2.5">Checklist</span><span class="p-2.5">Documents</span></div></aside>
            <div class="p-4 sm:p-7"><div class="flex items-center justify-between"><div><p class="text-xs text-slate-400">Good morning, Maya</p><h3 class="mt-1 text-xl font-extrabold text-[#17136b]">Your scholarship journey</h3></div><span class="hidden rounded-full bg-violet-100 px-3 py-1.5 text-xs font-bold text-[#5b45f5] sm:inline">Profile 86%</span></div>
              <div class="mt-6 grid gap-4 md:grid-cols-[1.3fr_.7fr]"><div class="dash-card"><div class="flex items-center justify-between"><p class="text-sm font-extrabold text-[#17136b]">Top recommendations</p><span class="text-xs font-bold text-[#5b45f5]">View all</span></div><div v-for="item in scholarships.slice(0,3)" :key="item.id" class="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><div class="min-w-0"><p class="truncate text-sm font-bold text-[#17136b]">{{ item.name }}</p><p class="mt-1 text-xs text-slate-400">{{ item.country }} · {{ item.fundingType }}</p></div><span class="ml-3 rounded-full bg-emerald-50 px-2 py-1 text-xs font-extrabold text-emerald-600">{{ item.matchPercentage }}%</span></div></div>
                <div class="grid gap-4"><div class="dash-card"><p class="text-sm font-extrabold text-[#17136b]">Application progress</p><div class="mt-4"><BaseProgress :value="62" label="Chevening" /></div><p class="mt-3 text-xs text-slate-400">5 of 8 requirements ready</p></div><div class="dash-card bg-gradient-to-br from-[#251878] to-[#5b45f5] text-white"><div class="flex items-center gap-2 text-xs font-bold text-violet-200"><WandSparkles :size="15" /> Minerva suggestion</div><p class="mt-3 text-sm font-semibold leading-5">Draft your leadership essay this week to leave time for mentor feedback.</p></div></div></div>
              <div class="mt-4 grid gap-4 sm:grid-cols-3"><div class="dash-card"><Bookmark :size="18" class="text-[#5b45f5]"/><p class="mt-3 text-2xl font-extrabold text-[#17136b]">7</p><p class="text-xs text-slate-400">Saved scholarships</p></div><div class="dash-card"><CircleCheck :size="18" class="text-emerald-500"/><p class="mt-3 text-2xl font-extrabold text-[#17136b]">62%</p><p class="text-xs text-slate-400">Checklist ready</p></div><div class="dash-card"><CalendarDays :size="18" class="text-[#27a8f7]"/><p class="mt-3 text-2xl font-extrabold text-[#17136b]">24 days</p><p class="text-xs text-slate-400">Next deadline</p></div></div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="border-y border-slate-200 bg-white py-12"><div class="container"><p class="text-center text-sm font-extrabold text-[#17136b]">Built for every step of your scholarship journey</p><div class="mt-7 grid sm:grid-cols-2 lg:grid-cols-4"><div v-for="(item,index) in ['Personalized Matching','Guided Preparation','Application Tracking','AI-Powered Feedback']" :key="item" class="value-tile"><span class="text-xs font-extrabold text-[#5b45f5]">0{{ index + 1 }}</span><p class="mt-2 font-bold text-[#17136b]">{{ item }}</p></div></div></div></section>

    <section id="product" class="section"><div class="container grid items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeader eyebrow="One platform, complete support" title="From scholarship search to application readiness" body="Stop switching between scattered websites, spreadsheets, document tools, and preparation platforms. Minerva brings everything together in one guided experience."/><div class="mt-8 grid"><button v-for="(feature,index) in features" :key="feature.label" class="feature-tab" :class="activeFeature === index && 'active'" @click="activeFeature = index">{{ feature.label }}</button></div></div><div class="story-panel"><div class="flex h-full min-h-[420px] flex-col rounded-3xl border border-white bg-white/70 p-6 shadow-sm sm:p-9"><component :is="features[activeFeature].icon" :size="28" class="text-[#5b45f5]"/><h3 class="mt-8 max-w-md text-3xl font-extrabold tracking-tight text-[#17136b]">{{ features[activeFeature].title }}</h3><p class="mt-4 max-w-lg leading-7 text-slate-500">{{ features[activeFeature].body }}</p><div class="mt-auto grid gap-3 pt-10 sm:grid-cols-2"><div v-for="n in 4" :key="n" class="dash-card flex items-center gap-3"><CircleCheck :size="17" class="text-emerald-500"/><span class="text-sm font-bold text-[#17136b]">{{ ['Clear next steps','Profile-aware guidance','Saved across pages','Frontend demo'][n-1] }}</span></div></div></div></div></div></section>

    <section class="section-soft"><div class="container"><SectionHeader eyebrow="Personalized discovery" title="Discover scholarships that fit you" body="Tell Minerva about your education, study goals, preferred destination, field, funding needs, and English proficiency. Minerva surfaces relevant opportunities and explains why they match."/><div class="mt-12 grid gap-5 lg:grid-cols-3"><ScholarshipCard v-for="item in scholarships.slice(0,3)" :key="item.id" :scholarship="item"/></div><div class="mt-9 flex flex-col items-start justify-between gap-5 border-t border-slate-200 pt-7 sm:flex-row sm:items-center"><p class="text-sm text-slate-500">Recommendations are guidance and do not guarantee acceptance.</p><RouterLink to="/onboarding" class="btn-primary">Find My Matches <ArrowRight :size="17"/></RouterLink></div></div></section>

    <section class="section"><div class="container"><div class="grid items-end gap-8 lg:grid-cols-2"><SectionHeader eyebrow="Focused search" title="Search less. Find better opportunities." body="Explore scholarships by destination, study level, field, funding type, category, and deadline."/><div class="relative"><Search class="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" :size="19"/><input v-model="query" class="field pl-12" aria-label="Search scholarships" placeholder="Try “Germany” or “STEM”"></div></div><div class="mt-10 grid gap-5 lg:grid-cols-3"><ScholarshipCard v-for="item in searchResults" :key="item.id" :scholarship="item" compact/><div v-if="!searchResults.length" class="card col-span-full p-12 text-center"><Search class="mx-auto text-slate-300"/><h3 class="mt-4 font-extrabold text-[#17136b]">No close matches yet</h3><p class="mt-2 text-sm text-slate-500">Try a broader destination or field.</p></div></div><div class="mt-8 text-center"><RouterLink to="/scholarships" class="btn-secondary">Open advanced search <ArrowRight :size="16"/></RouterLink></div></div></section>

    <section class="section-soft"><div class="container grid items-center gap-14 lg:grid-cols-2"><div><SectionHeader eyebrow="Stay organized" title="Know exactly what to prepare" body="Choose a scholarship and Minerva creates a practical checklist. Use documents you already have or open optional preparation tools when you need help."/><RouterLink to="/checklist" class="btn-primary mt-8">Build My Checklist <ArrowRight :size="17"/></RouterLink></div><div class="card p-6 sm:p-8"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Chevening Scholarship</p><h3 class="mt-2 text-xl font-extrabold text-[#17136b]">Application checklist</h3></div><span class="badge">Deadline Nov 3</span></div><div class="mt-6"><BaseProgress :value="progress" label="Preparation progress"/></div><div class="mt-6 grid gap-2"><label v-for="item in checklist.slice(0,5)" :key="item.id" class="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-100 p-3.5"><input v-model="item.completed" type="checkbox" class="size-4 accent-[#5b45f5]"><span class="text-sm font-semibold text-[#17136b]">{{ item.title }}</span><span class="ml-auto text-[10px] font-bold uppercase text-slate-400">{{ item.required ? 'Required' : 'Optional' }}</span></label></div><p class="mt-5 text-xs text-slate-400">Preparation tools are optional. You can mark any item complete yourself.</p></div></div></section>

    <section class="section"><div class="container"><SectionHeader eyebrow="Stronger applications" title="Improve your documents before you submit" body="Use local, simulated review experiences for more structured CVs and essays. Nothing is uploaded." align="center"/><div class="mx-auto mt-12 grid max-w-4xl gap-5 md:grid-cols-2"><div class="card p-8"><FileText :size="26" class="text-[#5b45f5]"/><h3 class="mt-6 text-2xl font-extrabold text-[#17136b]">CV Review</h3><p class="mt-3 leading-7 text-slate-500">Feedback on completeness, formatting, education, experience, achievements, skills, and relevance.</p></div><div class="card p-8"><WandSparkles :size="26" class="text-[#27a8f7]"/><h3 class="mt-6 text-2xl font-extrabold text-[#17136b]">Essay Review</h3><p class="mt-3 leading-7 text-slate-500">Guidance on structure, clarity, grammar, motivation, personal impact, and goal alignment.</p></div></div><div class="mt-8 text-center"><RouterLink to="/documents" class="btn-primary">Review My Documents</RouterLink><p class="mt-4 text-xs text-slate-400">AI feedback supports preparation. You remain responsible for the final version.</p></div></div></section>

    <section class="section-soft"><div class="container"><SectionHeader title="Prepare for more than the paperwork" align="center"/><div class="mt-12 grid gap-5 md:grid-cols-3"><div v-for="tool in [{icon:Headphones,title:'Test Prep',body:'Build confidence with original TOPIK, IELTS, and TOEFL mini-exercises and explanations.',to:'/test-prep',cta:'Open Test Prep'},{icon:Target,title:'Interview Prep',body:'Practice scholarship-tailored questions with live controls and a face mimic demo.',to:'/interview-prep',cta:'Practice an Interview'},{icon:Users,title:'Mentorship',body:'Connect with mentors based on experience, expertise, service, price, and availability.',to:'/mentors',cta:'Find a Mentor'}]" :key="tool.title" class="card p-8"><component :is="tool.icon" :size="25" class="text-[#5b45f5]"/><h3 class="mt-6 text-xl font-extrabold text-[#17136b]">{{ tool.title }}</h3><p class="mt-3 min-h-20 leading-7 text-slate-500">{{ tool.body }}</p><RouterLink :to="tool.to" class="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-[#5b45f5]">{{ tool.cta }} <ArrowRight :size="15"/></RouterLink></div></div></div></section>

    <section class="section"><div class="container grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionHeader eyebrow="Your journey" title="From profile to application readiness" body="A guided path that still leaves every decision in your hands."/><div class="grid gap-3 sm:grid-cols-2"><div v-for="(step,index) in steps" :key="step[0]" class="flex gap-4 rounded-2xl border border-slate-200 p-5"><span class="step-num">{{ index+1 }}</span><div><h3 class="font-extrabold text-[#17136b]">{{ step[0] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ step[1] }}</p></div></div></div></div></section>

    <section class="section-soft"><div class="container grid items-center gap-14 lg:grid-cols-2"><div class="story-panel p-5"><div class="card h-full p-6"><div class="flex items-center justify-between"><h3 class="font-extrabold text-[#17136b]">Scholarship command center</h3><span class="badge">12 tokens</span></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><div v-for="item in [{n:'86%',l:'Profile complete'},{n:'7',l:'Saved scholarships'},{n:'62%',l:'Checklist progress'},{n:'B2',l:'IELTS level'}]" :key="item.l" class="dash-card"><p class="text-2xl font-extrabold text-[#17136b]">{{ item.n }}</p><p class="mt-1 text-xs text-slate-400">{{ item.l }}</p></div></div><div class="dash-card mt-4"><BaseProgress :value="62" label="Selected scholarship"/><p class="mt-4 text-sm font-bold text-[#17136b]">Next: Request your second recommendation letter</p></div></div></div><div><SectionHeader eyebrow="Everything in one place" title="Your scholarship command center" body="See your profile, recommendations, saved opportunities, selected scholarship, document feedback, practice progress, mentor status, tokens, and upcoming deadlines."/><RouterLink to="/dashboard" class="btn-primary mt-8">View Demo Dashboard <ArrowRight :size="17"/></RouterLink></div></div></section>

    <section class="section"><div class="container"><SectionHeader title="More than a scholarship database" align="center"/><div class="mt-12 grid gap-px overflow-hidden rounded-3xl border border-slate-200 bg-slate-200 md:grid-cols-4"><div v-for="item in [['Personalized','Recommendations based on your background, eligibility, and goals.'],['Guided','Clear preparation steps, requirements, and progress tracking.'],['All in one','Discovery, feedback, practice, mentorship, and tracking.'],['Supportive','Built to help aspiring scholars move forward with confidence.']]" :key="item[0]" class="bg-white p-7"><ShieldCheck :size="22" class="text-[#5b45f5]"/><h3 class="mt-5 font-extrabold text-[#17136b]">{{ item[0] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ item[1] }}</p></div></div></div></section>

    <section class="section-soft"><div class="container"><SectionHeader title="Start free. Upgrade when you need more support." align="center"/><div class="mx-auto mt-12 grid max-w-5xl gap-5 md:grid-cols-3"><div v-for="plan in [{name:'Free',status:'Free',items:['Scholarship profile','Search & recommendations','Saved scholarships','Application checklist'],featured:false},{name:'Premium',status:'Coming Soon',items:['More recommendations','CV and essay reviews','Interview & IELTS practice','Detailed feedback'],featured:true},{name:'Tokens',status:'Pricing to Be Announced',items:['Document reviews','Essay feedback','Interview practice','Advanced demo features'],featured:false}]" :key="plan.name" class="pricing-card" :class="plan.featured && 'featured'"><span class="badge">{{ plan.status }}</span><h3 class="mt-6 text-2xl font-extrabold text-[#17136b]">{{ plan.name }}</h3><ul class="mt-6 grid gap-3"><li v-for="item in plan.items" :key="item" class="flex gap-2 text-sm"><CircleCheck :size="17" class="text-emerald-500"/>{{ item }}</li></ul></div></div><p class="mt-7 text-center text-xs text-slate-400">Payment features in the MVP are simulations and do not process real money.</p><div class="mt-6 text-center"><RouterLink to="/pricing" class="btn-secondary">Compare plans</RouterLink></div></div></section>

    <section id="faq" class="section"><div class="container grid gap-14 lg:grid-cols-[.65fr_1.35fr]"><SectionHeader eyebrow="Questions, answered" title="Frequently asked questions" body="A clear view of what this frontend demo does—and what it does not."/><div><div v-for="(item,index) in faqs" :key="item[0]" class="border-b border-slate-200"><button class="flex w-full items-center justify-between gap-4 py-5 text-left font-extrabold text-[#17136b]" :aria-expanded="faq === index" @click="faq = faq === index ? null : index"><span>{{ item[0] }}</span><ChevronDown :size="18" class="transition-transform" :class="faq === index && 'rotate-180'"/></button><div v-if="faq === index" class="pb-5 pr-8 leading-7 text-slate-500">{{ item[1] }}</div></div></div></div></section>

    <section class="px-3 pb-3"><div class="mx-auto max-w-[1500px] overflow-hidden rounded-[32px] bg-gradient-to-br from-[#17136b] via-[#251878] to-[#5b45f5] px-6 py-20 text-center text-white sm:py-28"><p class="text-xs font-extrabold uppercase tracking-[.2em] text-violet-200">Find. Prepare. Succeed.</p><h2 class="mx-auto mt-6 max-w-4xl text-[clamp(2.7rem,6vw,5.6rem)] font-extrabold leading-[.98] tracking-[-.055em]">Your scholarship journey starts here.</h2><p class="mx-auto mt-6 max-w-2xl text-lg leading-8 text-violet-100">Discover opportunities that match your goals, prepare stronger applications, and keep every step organized with Minerva.</p><div class="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><RouterLink to="/register" class="btn-primary !bg-white !text-[#17136b]">Create Your Profile <ArrowRight :size="17"/></RouterLink><RouterLink to="/scholarships" class="btn-secondary !border-white/20 !bg-white/10 !text-white">Explore Scholarships</RouterLink></div></div></section>
  </main>
</template>
