<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight, Eye, EyeOff } from 'lucide-vue-next'
import { useAppState } from '../composables/useAppState'
const email=ref(''),password=ref(''),remember=ref(true),show=ref(false),loading=ref(false),error=ref('');const router=useRouter();const {session,profile}=useAppState()
const submit=()=>{error.value='';if(!/^\S+@\S+\.\S+$/.test(email.value)||password.value.length<6){error.value='Enter a valid email and a password with at least 6 characters.';return}loading.value=true;setTimeout(()=>{session.value={name:profile.value?.name||'Maya',email:email.value};router.push(profile.value?'/dashboard':'/onboarding')},700)}
</script>
<template><main class="grid min-h-[calc(100vh-72px)] lg:grid-cols-2"><section class="hidden bg-gradient-to-br from-[#17136b] to-[#5b45f5] p-14 text-white lg:flex lg:flex-col lg:justify-between"><img src="/minerva-logo.png" alt="Minerva" class="h-20 w-64 rounded-xl bg-white object-cover"><div><p class="text-sm font-extrabold uppercase tracking-[.2em] text-violet-200">Find. Prepare. Succeed.</p><h1 class="mt-6 max-w-xl text-6xl font-extrabold leading-[1.02] tracking-[-.05em]">Your next opportunity is closer than it feels.</h1><p class="mt-6 max-w-lg text-lg leading-8 text-violet-100">Return to your shortlist, application checklist, and preparation workspace.</p></div><p class="text-xs text-violet-300">Frontend demo · No real account is created</p></section><section class="grid place-items-center p-6 py-16"><form class="w-full max-w-md" @submit.prevent="submit"><p class="eyebrow">Welcome back</p><h1 class="mt-5 text-4xl font-extrabold tracking-tight text-[#17136b]">Log in to Minerva</h1><p class="mt-3 text-slate-500">Use any valid email and 6+ character password for this demo.</p><div class="mt-8 grid gap-5"><label class="field-label">Email<input v-model="email" type="email" autocomplete="email" class="field" placeholder="you@example.com"></label><label class="field-label">Password<span class="relative"><input v-model="password" :type="show?'text':'password'" autocomplete="current-password" class="field pr-12" placeholder="••••••••"><button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" :aria-label="show?'Hide password':'Show password'" @click="show=!show"><EyeOff v-if="show" :size="18"/><Eye v-else :size="18"/></button></span></label><div class="flex items-center justify-between text-sm"><label class="flex items-center gap-2"><input v-model="remember" type="checkbox" class="accent-[#5b45f5]">Remember me</label><button type="button" class="font-bold text-[#5b45f5]">Forgot password?</button></div><p v-if="error" class="error">{{ error }}</p><button class="btn-primary" type="submit" :disabled="loading">{{ loading?'Signing in…':'Log in' }}<ArrowRight :size="16"/></button></div><p class="mt-6 text-center text-sm text-slate-500">New to Minerva? <RouterLink to="/register" class="font-extrabold text-[#5b45f5]">Create an account</RouterLink></p></form></section></main></template>
