<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowRight, Eye, EyeOff } from 'lucide-vue-next'
import { normalizeUserProfile, useAppState } from '../composables/useAppState'
import { apiRequest } from '../api'
import GoogleSignInButton from '../components/common/GoogleSignInButton.vue'
const email=ref(''),password=ref(''),remember=ref(true),show=ref(false),loading=ref(false),error=ref('');const router=useRouter();const route=useRoute();const {session,profile,tokenBalance,hydrateWorkspace,resetUserState}=useAppState()
onMounted(() => {
  const logo = document.querySelector<HTMLImageElement>('img[alt="Minerva"]')
  if (!logo) return
  logo.classList.add('cursor-pointer')
  logo.addEventListener('click', () => router.push('/'))
})
const submit=async()=>{error.value='';if(!/^\S+@\S+\.\S+$/.test(email.value)||password.value.length<6){error.value='Enter a valid email and a password with at least 6 characters.';return}loading.value=true;try{const result=await apiRequest<{user:{id:string;name:string;email:string;role:string;tokenBalance:number;profileCompleted:boolean}}>('/api/auth/login',{method:'POST',body:{email:email.value,password:password.value,remember:remember.value}});resetUserState();session.value={id:result.user.id,name:result.user.name,email:result.user.email,role:result.user.role};tokenBalance.value=result.user.tokenBalance;if(result.user.profileCompleted){try{const saved=await apiRequest<{profile:typeof profile.value}>('/api/profile');if(saved.profile)profile.value=normalizeUserProfile(saved.profile)}catch{/* Profile can be completed later. */}}await hydrateWorkspace();const redirect=typeof route.query.redirect==='string'&&/^\/(?!\/)/.test(route.query.redirect)?route.query.redirect:'/dashboard';await router.push(result.user.profileCompleted?redirect:'/onboarding')}catch(reason){error.value=reason instanceof Error?reason.message:'Unable to log in.'}finally{loading.value=false}}
</script>
<template><main class="grid min-h-[calc(100vh-72px)] lg:grid-cols-2"><section class="hidden bg-gradient-to-br from-[#17136b] to-[#5b45f5] p-14 text-white lg:flex lg:flex-col lg:justify-between"><img src="/minerva-logo.png" alt="Minerva" class="h-20 w-64 rounded-xl bg-white object-cover"><div><p class="text-sm font-extrabold uppercase tracking-[.2em] text-violet-200">Find. Prepare. Succeed.</p><h1 class="mt-6 max-w-xl text-6xl font-extrabold leading-[1.02] tracking-[-.05em]">Your next opportunity is closer than it feels.</h1><p class="mt-6 max-w-lg text-lg leading-8 text-violet-100">Return to your shortlist, application checklist, and preparation workspace.</p></div><p class="text-xs text-violet-300">Your workspace is securely saved to your Minerva account.</p></section><section class="grid place-items-center p-6 py-16"><form class="w-full max-w-md" @submit.prevent="submit"><p class="eyebrow">Welcome back</p><h1 class="mt-5 text-4xl font-extrabold tracking-tight text-[#17136b]">Log in to Minerva</h1><p class="mt-3 text-slate-500">Use your Minerva account to continue.</p><div class="mt-8 grid gap-5"><label class="field-label">Email<input v-model="email" type="email" autocomplete="email" class="field" placeholder="you@example.com"></label><label class="field-label">Password<span class="relative"><input v-model="password" :type="show?'text':'password'" autocomplete="current-password" class="field pr-12" placeholder="••••••••"><button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" :aria-label="show?'Hide password':'Show password'" @click="show=!show"><EyeOff v-if="show" :size="18"/><Eye v-else :size="18"/></button></span></label><div class="flex items-center justify-between text-sm"><label class="flex items-center gap-2"><input v-model="remember" type="checkbox" class="accent-[#5b45f5]">Remember me</label><RouterLink to="/forgot-password" class="font-bold text-[#5b45f5]">Forgot password?</RouterLink></div><p v-if="error" class="error">{{ error }}</p><p v-if="route.query.error==='google_denied'" class="error">Google sign-in was cancelled.</p><button class="btn-primary" type="submit" :disabled="loading">{{ loading?'Signing in…':'Log in' }}<ArrowRight :size="16"/></button><div class="my-1 flex items-center gap-3 text-[.7rem] font-extrabold uppercase tracking-[.18em] text-slate-400"><span class="h-px flex-1 bg-slate-200"/><span>or</span><span class="h-px flex-1 bg-slate-200"/></div><GoogleSignInButton label="Sign in with Google" :next="typeof route.query.redirect==='string'?route.query.redirect:''"/></div><p class="mt-6 text-center text-sm text-slate-500">New to Minerva? <RouterLink to="/register" class="font-extrabold text-[#5b45f5]">Create an account</RouterLink></p></form></section></main></template>
