<script setup lang="ts">
import { computed, ref } from 'vue'
import { Star, CalendarDays, CheckCircle2, Users } from 'lucide-vue-next'
import SectionHeader from '../components/common/SectionHeader.vue'
import BaseModal from '../components/common/BaseModal.vue'
import { mentors } from '../data/mentors'
import type { Mentor } from '../types'
import { useAppState } from '../composables/useAppState'
const modal=ref(false),selected=ref<Mentor|null>(null),service=ref(''),date=ref(''),time=ref(''),notes=ref(''),success=ref(false)
const { booking, toast }=useAppState(); const minDate=computed(()=>new Date().toISOString().slice(0,10))
const openBooking=(mentor:Mentor)=>{selected.value=mentor;service.value=mentor.services[0]??'';time.value=mentor.availableTimes[0]??'';date.value='';notes.value='';success.value=false;modal.value=true}
const submit=()=>{if(!selected.value||!service.value||!date.value||!time.value)return;booking.value={mentorId:selected.value.id,mentorName:selected.value.name,service:service.value,date:date.value,time:time.value,notes:notes.value};success.value=true;toast('Your simulated mentor request is confirmed.')}
</script>
<template><main><section class="border-b border-slate-200 bg-gradient-to-b from-[#fff7e6] to-white py-18"><div class="container"><SectionHeader eyebrow="Support from experience" title="Meet mentors who’ve walked the path" body="Browse scholarship alumni by expertise, service, price, and availability. Booking is a local frontend simulation and does not charge you."/></div></section><section class="section pt-12"><div class="container"><div v-if="booking" class="mb-8 flex flex-col gap-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-3"><CheckCircle2 class="text-emerald-500"/><div><p class="font-extrabold text-emerald-900">Upcoming demo booking with {{ booking.mentorName }}</p><p class="mt-1 text-sm text-emerald-700">{{ booking.service }} · {{ booking.date }} at {{ booking.time }}</p></div></div><RouterLink to="/dashboard" class="text-sm font-bold text-emerald-800">View on dashboard</RouterLink></div><div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><article v-for="mentor in mentors" :key="mentor.id" class="card flex flex-col p-7"><div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-[#5b45f5] to-[#27a8f7] text-lg font-extrabold text-white">{{ mentor.initials }}</div><div><h2 class="text-xl font-extrabold text-[#17136b]">{{ mentor.name }}</h2><p class="mt-1 flex items-center gap-1 text-sm font-bold text-amber-500"><Star :size="15" fill="currentColor"/>{{ mentor.rating }}</p></div></div><p class="mt-6 text-sm font-extrabold text-[#5b45f5]">{{ mentor.expertise }}</p><p class="mt-2 text-sm font-semibold text-slate-500">{{ mentor.scholarshipExperience }}</p><p class="mt-4 min-h-18 text-sm leading-6 text-slate-500">{{ mentor.biography }}</p><div class="mt-5 flex flex-wrap gap-2"><span v-for="item in mentor.services" :key="item" class="tag">{{ item }}</span></div><div class="mt-auto flex items-end justify-between border-t border-slate-100 pt-6"><div><p class="text-xs text-slate-400">From</p><p class="font-extrabold text-[#17136b]">{{ mentor.sessionPrice }}</p></div><button class="btn-primary" @click="openBooking(mentor)"><CalendarDays :size="16"/>Book</button></div></article></div></div></section>
<BaseModal :open="modal" :title="success?'Booking requested':`Book ${selected?.name ?? 'mentor'}`" @close="modal=false"><div v-if="success" class="py-6 text-center"><div class="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50"><CheckCircle2 class="text-emerald-500" :size="34"/></div><h3 class="mt-6 text-2xl font-extrabold text-[#17136b]">You’re all set</h3><p class="mt-3 leading-7 text-slate-500">Your simulated request is saved in this browser and now appears on your dashboard.</p><button class="btn-primary mt-7" @click="modal=false">Done</button></div><form v-else class="grid gap-5" @submit.prevent="submit"><label class="field-label">Service<select v-model="service" class="field"><option v-for="item in selected?.services" :key="item">{{ item }}</option></select></label><label class="field-label">Date<input v-model="date" type="date" :min="minDate" class="field" required></label><label class="field-label">Available time<select v-model="time" class="field"><option v-for="item in selected?.availableTimes" :key="item">{{ item }}</option></select></label><label class="field-label">Notes (optional)<textarea v-model="notes" class="field min-h-24 resize-y" placeholder="What would you like to focus on?"></textarea></label><div class="rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-800">This is a frontend-only booking simulation. No payment is processed and no mentor is contacted.</div><button class="btn-primary" type="submit"><Users :size="16"/>Submit booking request</button></form></BaseModal></main></template>
