<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft, ArrowRight, Check, UserRound, GraduationCap, Target, Languages, Files, ClipboardCheck } from 'lucide-vue-next'
import type { UserProfile } from '../types'
import { useAppState } from '../composables/useAppState'
const router=useRouter();const {profile,session,toast}=useAppState();const step=ref(0);const error=ref('')
const steps=[{title:'Personal information',icon:UserRound},{title:'Education',icon:GraduationCap},{title:'Scholarship goals',icon:Target},{title:'English proficiency',icon:Languages},{title:'Available documents',icon:Files},{title:'Review profile',icon:ClipboardCheck}]
const form=reactive<UserProfile>(profile.value?{...profile.value,availableDocuments:[...profile.value.availableDocuments]}:{name:session.value?.name||'',age:null,country:'Indonesia',destinationCountry:'',currentEducationLevel:'',targetEducationLevel:'Master',fieldOfStudy:'',scholarshipType:'Government',fundingPreference:'Fully funded',englishLevel:'Intermediate',ieltsScore:'',availableDocuments:[],enrollmentYear:'2027'})
const docs=['CV','Essay / personal statement','Study plan','Recommendation letter','Academic transcript','IELTS certificate','Passport']
const validate=()=>{error.value='';if(step.value===0&&(!form.name.trim()||!form.age||form.age<15||!form.country)){error.value='Add your name, age (15+), and country.';return false}if(step.value===1&&(!form.currentEducationLevel||!form.targetEducationLevel||!form.fieldOfStudy)){error.value='Complete your current level, target level, and field.';return false}if(step.value===2&&(!form.destinationCountry||!form.scholarshipType||!form.fundingPreference||!form.enrollmentYear)){error.value='Complete your destination and scholarship goals.';return false}if(step.value===3&&!form.englishLevel){error.value='Choose your English proficiency level.';return false}return true}
const next=()=>{if(validate())step.value=Math.min(5,step.value+1)};const back=()=>{error.value='';step.value=Math.max(0,step.value-1)}
const submit=()=>{profile.value={...form,availableDocuments:[...form.availableDocuments]};toast('Your profile is ready. Welcome to Minerva!');router.push('/dashboard')}
const progress=computed(()=>Math.round(((step.value+1)/steps.length)*100))
</script>
<template><main class="bg-[#fbfbfe] py-10 sm:py-16"><div class="container max-w-6xl"><div class="grid gap-8 lg:grid-cols-[280px_1fr]"><aside class="card h-max p-5 lg:sticky lg:top-24"><img src="/minerva-logo.png" alt="Minerva" class="h-14 w-44 object-contain"><p class="mt-7 text-xs font-extrabold uppercase tracking-wider text-slate-400">Profile progress · {{ progress }}%</p><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-gradient-to-r from-[#5b45f5] to-[#27a8f7] transition-all" :style="{width:`${progress}%`}"/></div><div class="mt-6 grid gap-2"><button v-for="(item,index) in steps" :key="item.title" class="flex items-center gap-3 rounded-xl p-3 text-left text-sm font-bold" :class="index===step?'bg-violet-50 text-[#5b45f5]':index<step?'text-emerald-600':'text-slate-400'" :disabled="index>step" @click="index<step&&(step=index)"><span class="grid size-8 place-items-center rounded-lg bg-white"><Check v-if="index<step" :size="16"/><component :is="item.icon" v-else :size="16"/></span><span class="hidden lg:inline">{{ item.title }}</span></button></div></aside>
<section class="card min-h-[650px] p-6 sm:p-10"><div><p class="eyebrow">Step {{ step+1 }} of {{ steps.length }}</p><h1 class="mt-5 text-3xl font-extrabold tracking-tight text-[#17136b]">{{ steps[step]?.title }}</h1><p class="mt-3 text-slate-500">{{ ['Let’s start with the basics Minerva will use in your demo profile.','Tell us where you are now and where you want your education to go.','Shape the opportunity filters around your goals and preferred support.','Add a rough English level. Practice results remain unofficial.','Select anything you already have. You can change this later.','Check your answers before creating your local demo profile.'][step] }}</p></div>
<div class="mt-9"><div v-if="step===0" class="grid gap-5 sm:grid-cols-2"><label class="field-label sm:col-span-2">Full name<input v-model="form.name" class="field" autocomplete="name" placeholder="Your full name"></label><label class="field-label">Age<input v-model.number="form.age" type="number" min="15" max="80" class="field" placeholder="21"></label><label class="field-label">Country<input v-model="form.country" class="field" placeholder="Indonesia"></label></div>
<div v-else-if="step===1" class="grid gap-5 sm:grid-cols-2"><label class="field-label">Current education level<select v-model="form.currentEducationLevel" class="field"><option value="">Select level</option><option>High school</option><option>Bachelor</option><option>Master</option></select></label><label class="field-label">Target education level<select v-model="form.targetEducationLevel" class="field"><option>Bachelor</option><option>Master</option><option>Doctorate</option><option>Postgraduate</option></select></label><label class="field-label sm:col-span-2">Field of study<input v-model="form.fieldOfStudy" class="field" placeholder="Public Policy, Computer Science, Education…"></label></div>
<div v-else-if="step===2" class="grid gap-5 sm:grid-cols-2"><label class="field-label">Destination country<select v-model="form.destinationCountry" class="field"><option value="">Choose destination</option><option>United Kingdom</option><option>Australia</option><option>United States</option><option>Germany</option><option>Japan</option><option>Europe</option><option>Open to anywhere</option></select></label><label class="field-label">Enrollment year<select v-model="form.enrollmentYear" class="field"><option>2027</option><option>2028</option><option>2029</option></select></label><label class="field-label">Scholarship type<select v-model="form.scholarshipType" class="field"><option>Government</option><option>University</option><option>International</option><option>Open to all</option></select></label><label class="field-label">Funding preference<select v-model="form.fundingPreference" class="field"><option>Fully funded</option><option>Partial funding</option><option>Either</option></select></label></div>
<div v-else-if="step===3" class="grid gap-5 sm:grid-cols-2"><label class="field-label">English-language level<select v-model="form.englishLevel" class="field"><option>Beginner</option><option>Intermediate</option><option>Upper intermediate</option><option>Advanced</option><option>Native / bilingual</option></select></label><label class="field-label">IELTS score (optional)<input v-model="form.ieltsScore" class="field" placeholder="e.g. 6.5"></label><div class="sm:col-span-2 rounded-2xl bg-amber-50 p-5 text-sm leading-6 text-amber-800">You can continue without an IELTS score. Minerva’s practice features are optional and do not provide official certification.</div></div>
<div v-else-if="step===4" class="grid gap-3 sm:grid-cols-2"><label v-for="doc in docs" :key="doc" class="flex cursor-pointer items-center gap-3 rounded-2xl border border-slate-200 p-4 font-bold text-[#17136b]" :class="form.availableDocuments.includes(doc)&&'border-violet-300 bg-violet-50'"><input v-model="form.availableDocuments" type="checkbox" :value="doc" class="accent-[#5b45f5]">{{ doc }}</label><p class="mt-3 text-sm text-slate-500 sm:col-span-2">Nothing selected? That’s okay. The checklist can still be completed manually later.</p></div>
<div v-else class="grid gap-5 sm:grid-cols-2"><div v-for="item in [['Name',form.name],['Age',String(form.age??'')],['Country',form.country],['Destination',form.destinationCountry],['Current education',form.currentEducationLevel],['Target education',form.targetEducationLevel],['Field',form.fieldOfStudy],['Funding',form.fundingPreference],['English level',form.englishLevel],['Enrollment year',form.enrollmentYear]]" :key="item[0]" class="rounded-2xl border border-slate-200 p-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">{{ item[0] }}</p><p class="mt-2 font-extrabold text-[#17136b]">{{ item[1]||'Not provided' }}</p></div><div class="rounded-2xl border border-slate-200 p-5 sm:col-span-2"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Available documents</p><div class="mt-3 flex flex-wrap gap-2"><span v-for="doc in form.availableDocuments" :key="doc" class="tag">{{ doc }}</span><span v-if="!form.availableDocuments.length" class="text-sm text-slate-400">None selected yet</span></div></div></div></div>
<p v-if="error" class="error mt-6 rounded-xl bg-red-50 p-4">{{ error }}</p><div class="mt-10 flex flex-col-reverse gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:justify-between"><button class="btn-secondary" :class="step===0&&'invisible'" @click="back"><ArrowLeft :size="16"/>Back</button><button v-if="step<5" class="btn-primary" @click="next">Continue<ArrowRight :size="16"/></button><button v-else class="btn-primary" @click="submit">Save profile & open dashboard<Check :size="16"/></button></div></section></div></div></main></template>
