<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight, CheckCircle2 } from 'lucide-vue-next'
import { useAppState } from '../composables/useAppState'
const name=ref(''),email=ref(''),password=ref(''),confirm=ref(''),terms=ref(false),loading=ref(false),errors=ref<string[]>([]);const router=useRouter();const {session}=useAppState()
const submit=()=>{errors.value=[];if(name.value.trim().length<2)errors.value.push('Enter your name.');if(!/^\S+@\S+\.\S+$/.test(email.value))errors.value.push('Enter a valid email.');if(password.value.length<8)errors.value.push('Use at least 8 characters for your password.');if(password.value!==confirm.value)errors.value.push('Passwords do not match.');if(!terms.value)errors.value.push('Accept the demo terms to continue.');if(errors.value.length)return;loading.value=true;setTimeout(()=>{session.value={name:name.value,email:email.value};router.push('/onboarding')},700)}
</script>
<template><main class="grid min-h-[calc(100vh-72px)] lg:grid-cols-2"><section class="grid place-items-center p-6 py-16"><form class="w-full max-w-md" @submit.prevent="submit"><p class="eyebrow">Start your journey</p><h1 class="mt-5 text-4xl font-extrabold tracking-tight text-[#17136b]">Create your Minerva profile</h1><p class="mt-3 text-slate-500">This simulated account is stored only in your browser.</p><div class="mt-8 grid gap-5"><label class="field-label">Name<input v-model="name" class="field" autocomplete="name" placeholder="Your full name"></label><label class="field-label">Email<input v-model="email" type="email" class="field" autocomplete="email" placeholder="you@example.com"></label><label class="field-label">Password<input v-model="password" type="password" class="field" autocomplete="new-password" placeholder="At least 8 characters"></label><label class="field-label">Confirm password<input v-model="confirm" type="password" class="field" autocomplete="new-password" placeholder="Repeat your password"></label><label class="flex items-start gap-3 text-sm leading-6"><input v-model="terms" type="checkbox" class="mt-1 accent-[#5b45f5]"><span>I agree to the demo terms and understand no real account is created.</span></label><ul v-if="errors.length" class="rounded-xl bg-red-50 p-4 text-xs text-red-700"><li v-for="item in errors" :key="item">• {{ item }}</li></ul><button class="btn-primary" type="submit" :disabled="loading">{{ loading?'Creating demo account…':'Create account' }}<ArrowRight :size="16"/></button></div><p class="mt-6 text-center text-sm text-slate-500">Already have an account? <RouterLink to="/login" class="font-extrabold text-[#5b45f5]">Log in</RouterLink></p></form></section><section class="hidden bg-gradient-to-br from-[#f3f1ff] to-[#eff8ff] p-14 lg:flex lg:flex-col lg:justify-center"><div class="mx-auto max-w-lg"><img src="/minerva-logo.png" alt="Minerva" class="h-18 w-64 object-contain"><h2 class="mt-12 text-5xl font-extrabold leading-tight tracking-[-.045em] text-[#17136b]">A clear path from discovery to readiness.</h2><div class="mt-9 grid gap-5"><div v-for="item in ['Personalized scholarship matches','Practical application checklists','Optional preparation tools','Progress stored on this device']" :key="item" class="flex items-center gap-3 font-bold text-[#17136b]"><CheckCircle2 class="text-emerald-500" :size="20"/>{{ item }}</div></div></div></section></main></template>
