<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Search, SlidersHorizontal, X, Sparkles } from 'lucide-vue-next'
import SectionHeader from '../components/common/SectionHeader.vue'
import ScholarshipCard from '../components/scholarships/ScholarshipCard.vue'
import { scholarships } from '../data/scholarships'

const loading = ref(true), query = ref(''), country = ref(''), level = ref(''), funding = ref(''), sort = ref('match')
onMounted(() => window.setTimeout(() => { loading.value = false }, 650))
const countries = [...new Set(scholarships.map((item) => item.country))]
const results = computed(() => scholarships.filter((item) => {
  const haystack = `${item.name} ${item.provider} ${item.country} ${item.fieldOfStudy} ${item.program}`.toLowerCase()
  return haystack.includes(query.value.toLowerCase()) && (!country.value || item.country === country.value) && (!level.value || item.educationLevel === level.value) && (!funding.value || item.fundingType === funding.value)
}).sort((a,b) => sort.value === 'name' ? a.name.localeCompare(b.name) : sort.value === 'deadline' ? a.deadline.localeCompare(b.deadline) : b.matchPercentage-a.matchPercentage))
const clear = () => { query.value=''; country.value=''; level.value=''; funding.value=''; sort.value='match' }
</script>
<template><main><section class="border-b border-slate-200 bg-gradient-to-b from-[#f6f4ff] to-white py-20"><div class="container"><SectionHeader eyebrow="Scholarship discovery" title="Find opportunities built for your next chapter" body="Search 12 curated demo scholarships by destination, level, field, and funding. Save promising options or open details to prepare."/><div class="mt-9 flex flex-wrap gap-2"><span class="badge"><Sparkles :size="14"/> Profile-aware demo matches</span><span class="tag">No account needed</span><span class="tag">Local-only saved state</span></div></div></section>
<section class="section pt-12"><div class="container"><div class="card p-4 sm:p-5"><div class="grid gap-3 lg:grid-cols-[1.6fr_repeat(3,1fr)]"><label class="relative"><span class="sr-only">Search scholarships</span><Search class="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" :size="18"/><input v-model="query" class="field pl-11" placeholder="Search by name, country, or field"></label><label><span class="sr-only">Country</span><select v-model="country" class="field"><option value="">All destinations</option><option v-for="item in countries" :key="item">{{ item }}</option></select></label><label><span class="sr-only">Study level</span><select v-model="level" class="field"><option value="">All study levels</option><option>Master</option><option>Postgraduate</option></select></label><label><span class="sr-only">Funding</span><select v-model="funding" class="field"><option value="">All funding</option><option>Fully funded</option><option>Partial funding</option></select></label></div><div class="mt-4 flex flex-wrap items-center gap-2"><SlidersHorizontal :size="16" class="text-[#5b45f5]"/><span v-if="country" class="badge">{{ country }} <button aria-label="Remove country filter" @click="country=''">×</button></span><span v-if="level" class="badge">{{ level }} <button aria-label="Remove level filter" @click="level=''">×</button></span><span v-if="funding" class="badge">{{ funding }} <button aria-label="Remove funding filter" @click="funding=''">×</button></span><button v-if="query || country || level || funding" class="ml-auto inline-flex items-center gap-1 text-xs font-bold text-slate-500" @click="clear"><X :size="14"/> Clear filters</button></div></div>
<div class="mt-9 flex items-center justify-between gap-4"><p class="font-extrabold text-[#17136b]">{{ results.length }} scholarships</p><label class="flex items-center gap-2 text-sm font-semibold text-slate-500">Sort by <select v-model="sort" class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-[#17136b]"><option value="match">Best match</option><option value="deadline">Deadline</option><option value="name">Name</option></select></label></div>
<div v-if="loading" class="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><div v-for="n in 6" :key="n" class="h-[335px] animate-pulse rounded-3xl bg-slate-100"/></div><div v-else-if="results.length" class="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><ScholarshipCard v-for="item in results" :key="item.id" :scholarship="item"/></div><div v-else class="card mt-7 p-16 text-center"><Search class="mx-auto text-slate-300" :size="34"/><h2 class="mt-5 text-2xl font-extrabold text-[#17136b]">No scholarships match those filters</h2><p class="mt-2 text-slate-500">Try clearing a filter or using a broader search term.</p><button class="btn-primary mt-6" @click="clear">Clear all filters</button></div></div></section></main></template>
