<script setup lang="ts">
import { computed, ref } from 'vue'
import { BookOpenCheck, CheckCircle2, ChevronRight, Headphones, RotateCcw, Sparkles } from 'lucide-vue-next'
import WorkspaceSidebar from '../components/dashboard/WorkspaceSidebar.vue'
import WorkspaceTopbar from '../components/dashboard/WorkspaceTopbar.vue'
import { useAppState } from '../composables/useAppState'
import { getScholarship } from '../data/scholarships'
const { practiceResult, toast, selectedId } = useAppState();const selected=computed(()=>selectedId.value?getScholarship(selectedId.value):undefined);const answer=ref(''),submitted=ref(false),skill=ref('Reading');const question=computed(()=>({Reading:'A scholarship committee values sustained service over isolated volunteering. Which statement best summarizes this?',Listening:'The information session moved from Hall B to the library auditorium at 3:30 PM. Where and when is it?',Speaking:`Describe a leadership experience that supports your application to ${selected.value?.name}.`,Writing:`Explain how your study plan will create measurable impact after completing ${selected.value?.program}.`}[skill.value]));const choices=[{id:'a',text:'One impressive activity is always more valuable.'},{id:'b',text:'Long-term service can show deeper commitment.'},{id:'c',text:'Only academic results matter.'}];const submit=()=>{if(!answer.value)return;submitted.value=true;practiceResult.value={type:'IELTS',score:answer.value==='b'?100:68,completedAt:new Date().toISOString(),explanation:'Use specific evidence and a clear main idea.'};toast(`IELTS practice saved to ${selected.value?.name}.`)};const reset=()=>{answer.value='';submitted.value=false}
</script>
<template><main class="workspace-shell"><WorkspaceSidebar active="test"/><div class="workspace-main"><WorkspaceTopbar title="IELTS Prep" subtitle="Focused IELTS preparation for the selected scholarship."/><div class="workspace-content"><section v-if="!selected" class="notion-select-state"><div class="notion-select-icon"><BookOpenCheck :size="31"/></div><p class="text-xs font-extrabold uppercase tracking-[.16em] text-[#5b45f5]">IELTS preparation</p><h1>Select a scholarship first</h1><p>Your IELTS study plan and results are saved per scholarship.</p><RouterLink to="/scholarships" class="btn-primary">Browse scholarships</RouterLink></section><template v-else><section class="ielts-hero"><div><p><Sparkles :size="15"/>IELTS focus plan</p><h2>Prepare for {{ selected.name }}</h2><span>{{ selected.provider }} · {{ selected.country }}</span></div><div class="ielts-band"><strong>{{ practiceResult?.score || '—' }}</strong><span>latest practice</span></div></section><nav class="ielts-skills"><button v-for="item in ['Reading','Listening','Speaking','Writing']" :key="item" :class="skill===item&&'active'" @click="skill=item;reset()">{{ item }}</button></nav><section class="mt-5 workspace-card p-6 sm:p-8"><div class="grid gap-8 xl:grid-cols-[1.2fr_.8fr]"><div><span class="badge">IELTS {{ skill }}</span><h2 class="mt-5 text-xl font-extrabold leading-8 text-[#17136b]">{{ question }}</h2><div v-if="skill==='Reading'" class="mt-6 grid gap-3"><label v-for="choice in choices" :key="choice.id" class="flex cursor-pointer gap-3 rounded-2xl border p-4" :class="answer===choice.id?'border-violet-400 bg-violet-50':'border-slate-200'"><input v-model="answer" type="radio" :value="choice.id" class="accent-[#5b45f5]"><span>{{ choice.text }}</span></label></div><textarea v-else v-model="answer" class="field mt-6 min-h-44" placeholder="Write your practice response here…"/><div class="mt-6 flex gap-3"><button class="btn-primary" @click="submit">Check practice<ChevronRight :size="16"/></button><button class="btn-secondary" @click="reset"><RotateCcw :size="16"/>Reset</button></div></div><aside class="rounded-2xl bg-[#f7f8fc] p-6"><BookOpenCheck v-if="!submitted" :size="34" class="text-[#a99af8]"/><CheckCircle2 v-else :size="34" class="text-emerald-500"/><h3 class="mt-4 font-extrabold text-[#17136b]">{{ submitted ? 'Practice saved' : 'Focused IELTS preparation' }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ submitted ? `Unofficial result: ${practiceResult?.score}%. Use the feedback to guide your next attempt.` : 'Complete one skill at a time. Results stay inside this scholarship folder.' }}</p></aside></div></section><p class="mt-5 flex gap-2 text-xs text-slate-400"><Headphones :size="15"/>Original simulated IELTS-style practice; not an official score.</p></template></div></div></main></template>
