<script setup lang="ts">
import { computed, ref } from 'vue'
import { BookOpenCheck, CheckCircle2, ChevronRight, Headphones, Languages, RotateCcw, Sparkles } from 'lucide-vue-next'
import WorkspaceSidebar from '../components/dashboard/WorkspaceSidebar.vue'
import WorkspaceTopbar from '../components/dashboard/WorkspaceTopbar.vue'
import { useAppState } from '../composables/useAppState'
import { getScholarship } from '../data/scholarships'

type TestId = 'topik' | 'ielts' | 'toefl'
const active = ref<TestId>('ielts')
const selectedAnswer = ref('')
const submitted = ref(false)
const { practiceResult, toast, selectedId } = useAppState()
const selected = computed(() => selectedId.value ? getScholarship(selectedId.value) : undefined)
const tests: Record<TestId, { label: string; question: string; choices: { id: string; text: string }[]; answer: string; tip: string }> = {
  topik: { label: 'Korean proficiency', question: 'Choose the best phrase for introducing yourself politely in Korean.', choices: [{ id: 'a', text: 'Annyeonghaseyo, jeoneun Mina-imnida.' }, { id: 'b', text: 'Hakgyoga chaegimnida.' }, { id: 'c', text: 'Oneureun eojjeimnida.' }], answer: 'a', tip: 'Focus on polite introductions and everyday vocabulary.' },
  ielts: { label: 'English proficiency', question: 'A scholarship committee values sustained service over isolated volunteering. Which statement best summarizes this?', choices: [{ id: 'a', text: 'One impressive activity is always more valuable.' }, { id: 'b', text: 'Long-term service can show deeper commitment.' }, { id: 'c', text: 'Only academic results matter to committees.' }], answer: 'b', tip: 'Use evidence from consistent activities when writing or speaking.' },
  toefl: { label: 'Academic English', question: 'A professor contrasts correlation with causation. What should a careful researcher avoid assuming?', choices: [{ id: 'a', text: 'Two related variables always cause one another.' }, { id: 'b', text: 'Evidence can be evaluated critically.' }, { id: 'c', text: 'Research questions need a clear scope.' }], answer: 'a', tip: 'Separate association from proof of cause in academic answers.' },
}
const current = computed(() => tests[active.value])
const reset = () => { selectedAnswer.value = ''; submitted.value = false }
const switchTest = (id: TestId) => { active.value = id; reset() }
const submit = () => { if (!selectedAnswer.value) return; submitted.value = true; const score = selectedAnswer.value === current.value.answer ? 100 : 60; practiceResult.value = { type: active.value.toUpperCase(), score, completedAt: new Date().toISOString(), explanation: current.value.tip }; toast(`${active.value.toUpperCase()} practice was saved to ${selected.value?.name}.`) }
</script>

<template>
  <main class="workspace-shell"><WorkspaceSidebar active="test"/><div class="workspace-main"><WorkspaceTopbar title="Test Prep" subtitle="Practice TOPIK, IELTS, and TOEFL for one scholarship at a time."/><div class="workspace-content">
    <section v-if="!selected" class="notion-select-state"><div class="notion-select-icon"><BookOpenCheck :size="31"/></div><p class="text-xs font-extrabold uppercase tracking-[.16em] text-[#5b45f5]">Test preparation</p><h1>Select a scholarship first</h1><p>Test choices and saved practice results remain separate for each scholarship application.</p><RouterLink to="/scholarships" class="btn-primary">Browse scholarships</RouterLink></section>
    <template v-else><p class="mb-5 text-sm font-extrabold text-[#17136b]"><span class="text-slate-400">Preparing for</span> {{ selected.name }} <span class="font-semibold text-slate-400">· {{ selected.provider }}</span></p><section class="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div class="rounded-3xl bg-[#17136b] p-6 text-white sm:p-8"><p class="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-violet-200"><Sparkles :size="15"/>Prep plan</p><h2 class="mt-5 text-3xl font-extrabold tracking-tight">Build confidence one skill at a time.</h2><p class="mt-4 max-w-md text-sm leading-7 text-violet-100">This study plan belongs only to your {{ selected.name }} application.</p><div class="mt-8 grid grid-cols-3 gap-3"><div v-for="item in [{n:'TOPIK',l:'Korean'},{n:'IELTS',l:'English'},{n:'TOEFL',l:'Academic'}]" :key="item.n" class="rounded-2xl bg-white/10 p-3"><p class="text-sm font-extrabold">{{ item.n }}</p><p class="mt-1 text-xs text-violet-200">{{ item.l }}</p></div></div></div><div class="workspace-card p-6"><p class="text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Choose a test</p><h2 class="mt-3 text-2xl font-extrabold text-[#17136b]">Practice what this application needs.</h2><div class="mt-5 grid gap-3 sm:grid-cols-3"><button v-for="(test,id) in tests" :key="id" class="test-card text-left" :class="active===id && 'border-violet-400 bg-violet-50'" @click="switchTest(id as TestId)"><Languages :size="18" class="text-[#5b45f5]"/><p class="mt-4 font-extrabold text-[#17136b]">{{ String(id).toUpperCase() }}</p><p class="mt-1 text-xs text-slate-500">{{ test.label }}</p></button></div></div></section>
      <section class="mt-6 workspace-card overflow-hidden"><div class="bg-gradient-to-r from-[#5b45f5] to-[#27a8f7] p-6 text-white sm:p-7"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-white/75">{{ current.label }}</p><h2 class="mt-3 text-3xl font-extrabold">{{ active.toUpperCase() }} practice room</h2></div><div class="p-5 sm:p-7"><div class="grid gap-7 xl:grid-cols-[1.15fr_.85fr]"><section><span class="badge">Mini exercise</span><h3 class="mt-5 text-xl font-extrabold leading-8 text-[#17136b]">{{ current.question }}</h3><div class="mt-6 grid gap-3"><label v-for="choice in current.choices" :key="choice.id" class="flex cursor-pointer gap-3 rounded-2xl border p-4" :class="selectedAnswer===choice.id?'border-violet-400 bg-violet-50':'border-slate-200'"><input v-model="selectedAnswer" type="radio" :value="choice.id" class="mt-1 accent-[#5b45f5]"><span class="text-sm font-semibold leading-6 text-[#17136b]">{{ choice.text }}</span></label></div><div class="mt-6 flex gap-3"><button class="btn-primary" @click="submit">Check answer <ChevronRight :size="16"/></button><button class="btn-secondary" @click="reset"><RotateCcw :size="16"/>Reset</button></div></section><aside class="rounded-2xl bg-[#f7f8fc] p-5"><div v-if="!submitted" class="grid min-h-56 place-items-center text-center"><div><BookOpenCheck class="mx-auto text-[#a99af8]" :size="34"/><h3 class="mt-4 font-extrabold text-[#17136b]">Ready when you are</h3></div></div><div v-else><CheckCircle2 :size="30" class="text-emerald-500"/><p class="mt-5 text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Saved for this scholarship</p><p class="mt-2 text-5xl font-extrabold text-[#5b45f5]">{{ practiceResult?.score }}<span class="text-xl text-slate-400">%</span></p><p class="mt-5 text-sm leading-6 text-slate-500">{{ current.tip }}</p></div></aside></div></div></section><p class="mt-5 flex items-start gap-2 text-xs leading-5 text-slate-400"><Headphones :size="15" class="mt-0.5 shrink-0"/>Minerva provides original, simulated practice only.</p></template>
  </div></div></main>
</template>
